name: Benchmark Reusable Workflow

on:
  workflow_call: 
    inputs: 
      git_username:
        required: true
        type: string
      public_repo_name:
        required: true
        type: string
      repo_owner:   
        required: true
        type: string
      email:
        required: true
        type: string
    secrets:
      GIT_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
    - name: Close previous server
      #run: echo "close"
      run: docker compose down
    - name: Launch server
      #run: echo "launch"
      run: docker compose up -d 
  
  check_energy_measurement:
    runs-on: [ self-hosted ]
    needs: build
    name: Energy Measurement
    steps:
    - uses: actions/checkout@v3
    - name: Start intel power log
      run: |
        $run_time=[int](([string](Powershell "Select-String -Path 'config.yaml' -Pattern 'run_time'").Split(' ')[2]) -replace '"','') * 60
        echo "Runtime measurement (seconds): $run_time"
        & "C:\Program Files\Intel\Power Gadget 3.6\PowerLog3.0.exe" -cmd "PowerShell Start-Sleep $run_time"
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: power_consumption
        path: PowerLog.csv
        
  execute_benchmark:
    needs: build
    runs-on: ubuntu-latest
    name: Benchmark API REST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Launch benchmark
        continue-on-error: true
        uses: econesag/api_benchmark@main
        id: benchmark
        env:
          config: config.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: html_benchmark
          path: report1.html
  
  filter_results:
    needs:
      - execute_benchmark
      - check_energy_measurement
    runs-on: ubuntu-latest
    name: Filter Results
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: power_consumption
      - uses: actions/download-artifact@v2
        with:
          name: html_benchmark
      - name: Launch benchmark
        uses: econesag/api_benchmark@main
        id: benchmark
        env:
          config: config.yaml
      - name: Check Python and Filter script
        run: |
          python3 --version
          echo Y29uc3VtcHRpb25fdGFibGUgPSAiPHN0eWxlPlxuLmNvbnRhaW5lcjIge1xud2lkdGg6IDEwMDBweDtcbm1hcmdpbjogMCBhdXRvO1xucGFkZGluZzogMTBweDtcbmJhY2tncm91bmQ6ICMxNzM1Mjk7XG4iCmNvbnN1bXB0aW9uX3RhYmxlICs9ICJmb250LWZhbWlseTogQXJpYWwsIEhlbHZldGljYSwgc2Fucy1zZXJpZjtcbmZvbnQtc2l6ZTogMTRweDtcbmNvbG9yOiAjZmZmO1xufVxuLmluZm8gc3BhbntcbiIKY29uc3VtcHRpb25fdGFibGUgKz0gImNvbG9yOiAjYjNjM2JjO1xufVxudGFibGUge1xuYm9yZGVyLWNvbGxhcHNlOiBjb2xsYXBzZTtcbnRleHQtYWxpZ246IGNlbnRlcjtcbndpZHRoOiAxMDAlO1xufVxudGQsIHRoIHtcbiIKY29uc3VtcHRpb25fdGFibGUgKz0gImJvcmRlcjogMXB4IHNvbGlkICNjYWQ5ZWE7XG5jb2xvcjogIzY2NjtcbmhlaWdodDogMzBweDtcbn1cbnRoZWFkIHRoIHtcbiIKY29uc3VtcHRpb25fdGFibGUgKz0gImJhY2tncm91bmQtY29sb3I6ICNjY2U4ZWI7XG53aWR0aDogMTAwcHg7XG59XG50cjpudGgtY2hpbGQob2RkKSB7XG5iYWNrZ3JvdW5kOiAjZmZmO1xufVxuIgpjb25zdW1wdGlvbl90YWJsZSArPSAidHI6bnRoLWNoaWxkKGV2ZW4pIHtcbmJhY2tncm91bmQ6ICNmNWZhZmE7XG59XG4uY2hhcnRzLWNvbnRhaW5lciAuY2hhcnQge1xud2lkdGg6IDEwMCU7XG4iCmNvbnN1bXB0aW9uX3RhYmxlICs9ICJoZWlnaHQ6IDM1MHB4O1xubWFyZ2luLWJvdHRvbTogMzBweDtcbn1cbi5kb3dubG9hZCB7XG5mbG9hdDogcmlnaHQ7XG59XG4uZG93bmxvYWQgYSB7XG4iCmNvbnN1bXB0aW9uX3RhYmxlICs9ICJjb2xvcjogIzAwY2E1YTtcbn1cbi5ncmFwaCB7XG5tYXJnaW4tYm90dG9tOiAxZW07XG59XG48L3N0eWxlPlxuPGRpdiBjbGFzcz1cImNvbnRhaW5lcjJcIj5cbiIKY29uc3VtcHRpb25fdGFibGUgKz0gIjxoMj5Qb3dlciBDb25zdW1wdGlvbiBNZXRyaWNzPC9oMj5cbjx0YWJsZSBjbGFzcz1cImRlZmF1bHRcIj5cbiI7IGlzX21ldHJpY3MgPSBGYWxzZQp3aXRoIG9wZW4oIlBvd2VyTG9nLmNzdiIsICJyIiwgZW5jb2Rpbmc9J3V0Zi04JykgYXMgZjogCiAgICBmb3IgbGluZSBpbiBmOgogICAgICAgIGlmICdUb3RhbCBFbGFwc2VkIFRpbWUnIGluIGxpbmU6IGlzX21ldHJpY3MgPSBUcnVlCiAgICAgICAgaWYgaXNfbWV0cmljcyBhbmQgbGVuKGxpbmUuc3BsaXQoJyA9ICcpKSA+IDEgYW5kICgnVGltZScgaW4gbGluZSBvciAnRnJlcXVlbmN5JyBpbiBsaW5lIG9yICdQcm9jZXNzb3InIGluIGxpbmUpOgogICAgICAgICAgICBjb25zdW1wdGlvbl90YWJsZSArPSAiPHRyPlxuIjsgY29uc3VtcHRpb25fdGFibGUgKz0gIjx0ZD4iK2xpbmUuc3BsaXQoJyA9ICcpWzBdKyI8L3RkPlxuIgogICAgICAgICAgICBjb25zdW1wdGlvbl90YWJsZSArPSAiPHRkPiIrbGluZS5zcGxpdCgnID0gJylbMV0rIjwvdGQ+XG4iOyBjb25zdW1wdGlvbl90YWJsZSArPSAiPC90cj5cbiIKICAgIGNvbnN1bXB0aW9uX3RhYmxlICs9ICI8L3RhYmxlPlxuPC9ib2R5PiIKaW1wb3J0IG9zOyBvcy5yZW1vdmUoIlBvd2VyTG9nLmNzdiIpCndpdGggb3BlbigicmVwb3J0MS5odG1sIiwgInIiLCBlbmNvZGluZz0ndXRmLTgnKSBhcyBmOiBjbGVhbl9odG1sID0gZi5yZWFkKCk7IGNsZWFuX2h0bWw9Y2xlYW5faHRtbC5yZXBsYWNlKCc8L2JvZHk+JywgY29uc3VtcHRpb25fdGFibGUpCndpdGggb3BlbigicmVwb3J0MS5odG1sIiwgInciLCBlbmNvZGluZz0ndXRmLTgnKSBhcyBmOiBmLndyaXRlKGNsZWFuX2h0bWwp | base64 -d > filter.py
          cat filter.py
      - name: Run Filter script
        run: |
          python3 filter.py
      - name: Deploy on public repo
        if: ${{ always() }}
        env:           
          REPO_OWNER: ${{ inputs.repo_owner }}
          USERNAME: ${{ inputs.git_username }}
          PUBLIC_REPO_NAME: ${{ inputs.public_repo_name }}
          EMAIL: ${{ inputs.email }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          # remove git settings and history
          rm -rf .git
          # use the new repo
          git init
          git config user.name $USERNAME
          git config user.email $EMAIL
          git config --global init.defaultBranch main
          # git remote add origin https://$USERNAME:$GIT_TOKEN@github.com/<repo_owner>/<repo_name>.git
          git remote add origin https://$USERNAME:$GIT_TOKEN@github.com/$REPO_OWNER/$PUBLIC_REPO_NAME.git
          mkdir docs
          cp -r *.html docs/
          cd docs
          cp *.html index.html
          cd ..
          git add docs
          git commit -m "New results of benchmark"
          git push origin HEAD:main --force
      
